#docker-compose.yml
version: "3"
  postgres:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DATABASE_DEV},${POSTGRES_DATABASE_TEST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

volumes:
  db-data:
